apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: api 
  name: api 
spec:
  replicas: 1
  selector:
    name: api 
  template:
    metadata:
      labels:
        name: api 
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: laurafitz/fypapi:bf5497a
        name: api 
        ports:
        - containerPort: 9292
          name: api 
          protocol: TCP 
        resources:
          limits:
            cpu: 100m
