apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    component: api
spec:
  selector:
    component: api
  clusterIP: None
  ports:
  - name: client
    port: 80
    targetPort: 8000
    nodePort: 31925
    protocol: TCP
  type: LoadBalancer
