FROM debian:latest

RUN apt-get update
RUN apt-get -y install rubygems ruby-dev build-essential libssl-dev 

RUN gem install bundler

RUN mkdir /app

ADD Gemfile /app/Gemfile
RUN cd /app && bundle install

VOLUME /app

WORKDIR /app

ENTRYPOINT ["rake"]
